// Code generated by goyacc -o parser.go -l staticlang.y. DO NOT EDIT.
// Package grammar contains the Yacc parser for StaticLang
package grammar

import __yyfmt__ "fmt"

import (
	"fmt"
	"strconv"

	"github.com/sokoide/llvm5/internal/domain"
	"github.com/sokoide/llvm5/internal/interfaces"
)

type yySymType struct {
	yys     int
	token   interfaces.Token
	program *domain.Program
	decl    domain.Declaration
	decls   []domain.Declaration
	stmt    domain.Statement
	stmts   []domain.Statement
	expr    domain.Expression
	exprs   []domain.Expression
	param   domain.Parameter
	params  []domain.Parameter
	field   domain.StructField
	fields  []domain.StructField
	typ     domain.Type
	str     string
	num     int64
	float   float64
	boolean bool
}

const IDENTIFIER = 57346
const FUNC = 57347
const STRUCT = 57348
const VAR = 57349
const IF = 57350
const ELSE = 57351
const WHILE = 57352
const FOR = 57353
const RETURN = 57354
const TRUE = 57355
const FALSE = 57356
const PLUS = 57357
const MINUS = 57358
const STAR = 57359
const SLASH = 57360
const PERCENT = 57361
const EQUAL = 57362
const NOT_EQUAL = 57363
const LESS = 57364
const LESS_EQUAL = 57365
const GREATER = 57366
const GREATER_EQUAL = 57367
const AND = 57368
const OR = 57369
const NOT = 57370
const ASSIGN = 57371
const LEFT_PAREN = 57372
const RIGHT_PAREN = 57373
const LEFT_BRACE = 57374
const RIGHT_BRACE = 57375
const LEFT_BRACKET = 57376
const RIGHT_BRACKET = 57377
const SEMICOLON = 57378
const COMMA = 57379
const DOT = 57380
const COLON = 57381
const ARROW = 57382
const EOF = 57383
const LOWER_THAN_ELSE = 57384
const UNARY_MINUS = 57385

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"FUNC",
	"STRUCT",
	"VAR",
	"IF",
	"ELSE",
	"WHILE",
	"FOR",
	"RETURN",
	"TRUE",
	"FALSE",
	"PLUS",
	"MINUS",
	"STAR",
	"SLASH",
	"PERCENT",
	"EQUAL",
	"NOT_EQUAL",
	"LESS",
	"LESS_EQUAL",
	"GREATER",
	"GREATER_EQUAL",
	"AND",
	"OR",
	"NOT",
	"ASSIGN",
	"LEFT_PAREN",
	"RIGHT_PAREN",
	"LEFT_BRACE",
	"RIGHT_BRACE",
	"LEFT_BRACKET",
	"RIGHT_BRACKET",
	"SEMICOLON",
	"COMMA",
	"DOT",
	"COLON",
	"ARROW",
	"EOF",
	"LOWER_THAN_ELSE",
	"UNARY_MINUS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

// Helper functions
func getLocationFromToken(token interfaces.Token) domain.SourceRange {
	pos := token.Location
	return domain.SourceRange{
		Start: pos,
		End:   pos,
	}
}

func getLocationFromString(str string) domain.SourceRange {
	// This is a placeholder - in a real implementation, we'd track positions
	return domain.SourceRange{
		Start: domain.SourcePosition{},
		End:   domain.SourcePosition{},
	}
}

func getLocation(decls []domain.Declaration) domain.SourceRange {
	if len(decls) == 0 {
		return domain.SourceRange{}
	}
	start := decls[0].GetLocation()
	end := decls[len(decls)-1].GetLocation()
	return domain.SourceRange{
		Start: start.Start,
		End:   end.End,
	}
}

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 264

var yyAct = [...]uint8{
	105, 69, 28, 153, 121, 70, 152, 45, 142, 71,
	122, 116, 114, 46, 36, 141, 9, 41, 10, 151,
	10, 126, 12, 7, 8, 15, 16, 17, 127, 143,
	140, 12, 7, 8, 82, 34, 25, 10, 29, 33,
	48, 44, 10, 35, 47, 10, 51, 10, 33, 78,
	54, 10, 11, 72, 73, 74, 12, 55, 76, 13,
	79, 11, 75, 10, 29, 18, 80, 10, 56, 57,
	58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
	68, 98, 99, 23, 50, 12, 11, 12, 102, 100,
	22, 123, 77, 104, 103, 10, 19, 24, 12, 12,
	83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
	93, 94, 95, 50, 50, 11, 124, 11, 21, 159,
	158, 49, 145, 42, 144, 154, 130, 52, 31, 12,
	101, 138, 132, 125, 133, 38, 32, 129, 135, 128,
	136, 137, 134, 10, 20, 149, 150, 39, 12, 43,
	146, 147, 155, 156, 148, 157, 27, 42, 42, 160,
	161, 115, 117, 30, 118, 119, 120, 53, 42, 38,
	38, 115, 117, 26, 118, 119, 120, 58, 59, 60,
	38, 39, 39, 43, 43, 3, 50, 96, 14, 131,
	139, 37, 39, 40, 43, 42, 50, 106, 115, 117,
	81, 118, 119, 120, 113, 112, 111, 38, 56, 57,
	58, 59, 60, 61, 62, 63, 64, 65, 66, 39,
	110, 43, 109, 50, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 42, 56, 57, 58,
	59, 60, 108, 107, 63, 64, 65, 66, 38, 56,
	57, 58, 59, 60, 2, 6, 5, 4, 1, 0,
	39, 0, 43, 97,
}

var yyPact = [...]int16{
	27, -1000, 18, -1000, -1000, -1000, -1000, 144, 144, 144,
	-1000, 61, -1000, -1000, -1000, 114, 86, 54, 62, 83,
	125, 95, -1000, 119, 83, -1000, -24, 81, -1000, 83,
	94, -1000, -1000, 83, 21, 53, -1000, -29, 119, 119,
	-1000, -1000, -1000, 119, -1000, 52, 144, 82, -1000, 83,
	-1000, -1000, -1000, -1000, -2, -1000, 119, 119, 119, 119,
	119, 119, 119, 119, 119, 119, 119, 119, 119, 232,
	119, 144, -1000, -1000, 99, 82, -1000, 83, -1000, -1000,
	82, 164, -1000, 160, 160, -1000, -1000, -1000, 222, 222,
	234, 234, 234, 234, 193, 209, -27, -1000, -1000, 56,
	-1000, -1000, -1000, 82, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 144, -8, 109, 107, 96,
	153, -1000, 119, -1000, -1000, 83, 119, -1000, 119, 119,
	154, -1000, -6, -1000, -21, -7, 93, 91, 119, 119,
	-1000, -1000, 119, -1000, 191, 191, -17, -30, -33, 116,
	-1000, 191, 191, -1000, 191, 89, 88, -1000, 191, 191,
	-1000, -1000,
}

var yyPgo = [...]int16{
	0, 258, 185, 257, 256, 255, 254, 0, 243, 242,
	222, 220, 206, 205, 204, 12, 200, 11, 193, 191,
	14, 43, 187, 2, 173, 136, 163, 16, 17,
}

var yyR1 = [...]int8{
	0, 1, 1, 6, 6, 2, 2, 2, 5, 5,
	3, 3, 3, 3, 3, 3, 4, 4, 24, 24,
	23, 26, 26, 25, 27, 27, 27, 16, 16, 7,
	7, 7, 7, 7, 7, 7, 7, 8, 8, 9,
	10, 10, 11, 12, 12, 13, 13, 14, 15, 17,
	21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	21, 21, 21, 21, 20, 20, 20, 19, 19, 19,
	19, 19, 22, 22, 18, 18, 18, 28,
}

var yyR2 = [...]int8{
	0, 2, 0, 1, 2, 1, 1, 1, 3, 5,
	7, 6, 6, 5, 8, 7, 5, 4, 1, 3,
	2, 1, 2, 3, 1, 4, 3, 0, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 4, 6, 4,
	5, 7, 5, 8, 8, 2, 3, 2, 3, 1,
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 1, 2, 2, 1, 4, 3,
	4, 3, 1, 3, 1, 1, 3, 1,
}

var yyChk = [...]int16{
	-1000, -1, -6, -2, -3, -4, -5, 5, 6, -27,
	-28, 34, 4, 41, -2, -28, -28, -28, 4, 35,
	30, 32, 36, 29, 35, -27, -24, 31, -23, -28,
	-26, 33, -25, -28, -17, -21, -20, -19, 16, 28,
	-18, -28, 4, 30, -27, 31, 37, -27, -15, 40,
	32, -27, 33, -25, -27, 36, 15, 16, 17, 18,
	19, 20, 21, 22, 23, 24, 25, 26, 27, 30,
	34, 38, -20, -20, -17, -27, -15, 40, -23, -15,
	-27, -16, 36, -21, -21, -21, -21, -21, -21, -21,
	-21, -21, -21, -21, -21, -21, -22, 31, -17, -17,
	-28, 31, -15, -27, -15, -7, 33, -8, -9, -10,
	-11, -12, -13, -14, -15, 7, -17, 8, 10, 11,
	12, 31, 37, 35, -15, -28, 29, 36, 30, 30,
	30, 36, -17, -17, -27, -17, -17, -17, -7, 36,
	36, 36, 29, 36, 31, 31, -17, -17, -17, -7,
	-7, 36, 36, 36, 9, -7, -7, -7, 31, 31,
	-7, -7,
}

var yyDef = [...]int8{
	2, -2, 0, 3, 5, 6, 7, 0, 0, 0,
	24, 0, 77, 1, 4, 0, 0, 0, 0, 0,
	0, 0, 8, 0, 0, 26, 0, 0, 18, 0,
	0, 17, 21, 0, 0, 49, 50, 64, 0, 0,
	67, 74, 75, 0, 25, 0, 0, 0, 13, 0,
	27, 20, 16, 22, 0, 9, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 65, 66, 0, 0, 12, 0, 19, 11,
	0, 0, 23, 51, 52, 53, 54, 55, 56, 57,
	58, 59, 60, 61, 62, 63, 0, 69, 72, 0,
	71, 76, 10, 0, 15, 28, 48, 29, 30, 31,
	32, 33, 34, 35, 36, 0, 0, 0, 0, 0,
	0, 68, 0, 70, 14, 0, 0, 47, 0, 0,
	0, 45, 0, 73, 0, 0, 0, 0, 0, 0,
	46, 37, 0, 39, 0, 0, 0, 0, 0, 40,
	42, 0, 0, 38, 0, 0, 0, 41, 0, 0,
	43, 44,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			ret := &domain.Program{
				BaseNode:     domain.BaseNode{Location: getLocation(yyDollar[1].decls)},
				Declarations: yyDollar[1].decls,
			}
			yylex.(*Parser).result = ret
			yyVAL.program = ret
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			ret := &domain.Program{
				BaseNode:     domain.BaseNode{},
				Declarations: []domain.Declaration{},
			}
			yylex.(*Parser).result = ret
			yyVAL.program = ret
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.decls = []domain.Declaration{yyDollar[1].decl}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.decls = append(yyDollar[1].decls, yyDollar[2].decl)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.decl = yyDollar[1].decl
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.decl = yyDollar[1].decl
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.decl = yyDollar[1].decl
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.decl = &domain.VarDeclStmt{
				BaseNode:    domain.BaseNode{Location: getLocationFromString(yyDollar[2].str)},
				Name:        yyDollar[2].str,
				Type_:       yyDollar[1].typ,
				Initializer: nil,
			}
		}
	case 9:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.decl = &domain.VarDeclStmt{
				BaseNode:    domain.BaseNode{Location: getLocationFromString(yyDollar[2].str)},
				Name:        yyDollar[2].str,
				Type_:       yyDollar[1].typ,
				Initializer: yyDollar[4].expr,
			}
		}
	case 10:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.decl = &domain.FunctionDecl{
				BaseNode:   domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Name:       yyDollar[2].str,
				Parameters: yyDollar[4].params,
				ReturnType: yyDollar[6].typ,
				Body:       yyDollar[7].stmt.(*domain.BlockStmt),
			}
		}
	case 11:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.decl = &domain.FunctionDecl{
				BaseNode:   domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Name:       yyDollar[2].str,
				Parameters: []domain.Parameter{},
				ReturnType: yyDollar[5].typ,
				Body:       yyDollar[6].stmt.(*domain.BlockStmt),
			}
		}
	case 12:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			// Default return type is int if no explicit type is provided
			reg := yylex.(*Parser).typeRegistry
			intType, _ := reg.GetType("int")
			yyVAL.decl = &domain.FunctionDecl{
				BaseNode:   domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Name:       yyDollar[2].str,
				Parameters: yyDollar[4].params,
				ReturnType: intType,
				Body:       yyDollar[6].stmt.(*domain.BlockStmt),
			}
		}
	case 13:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			// Default return type is int if no explicit type is provided
			reg := yylex.(*Parser).typeRegistry
			intType, _ := reg.GetType("int")
			yyVAL.decl = &domain.FunctionDecl{
				BaseNode:   domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Name:       yyDollar[2].str,
				Parameters: []domain.Parameter{},
				ReturnType: intType,
				Body:       yyDollar[5].stmt.(*domain.BlockStmt),
			}
		}
	case 14:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.decl = &domain.FunctionDecl{
				BaseNode:   domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Name:       yyDollar[2].str,
				Parameters: yyDollar[4].params,
				ReturnType: yyDollar[7].typ,
				Body:       yyDollar[8].stmt.(*domain.BlockStmt),
			}
		}
	case 15:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.decl = &domain.FunctionDecl{
				BaseNode:   domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Name:       yyDollar[2].str,
				Parameters: []domain.Parameter{},
				ReturnType: yyDollar[6].typ,
				Body:       yyDollar[7].stmt.(*domain.BlockStmt),
			}
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.decl = &domain.StructDecl{
				BaseNode: domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Name:     yyDollar[2].str,
				Fields:   yyDollar[4].fields,
			}
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.decl = &domain.StructDecl{
				BaseNode: domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Name:     yyDollar[2].str,
				Fields:   []domain.StructField{},
			}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.params = []domain.Parameter{yyDollar[1].param}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.params = append(yyDollar[1].params, yyDollar[3].param)
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.param = domain.Parameter{
				Name: yyDollar[1].str,
				Type: yyDollar[2].typ,
			}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.fields = []domain.StructField{yyDollar[1].field}
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.fields = append(yyDollar[1].fields, yyDollar[2].field)
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.field = domain.StructField{
				Name: yyDollar[1].str,
				Type: yyDollar[2].typ,
			}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			reg := yylex.(*Parser).typeRegistry
			if t, exists := reg.GetType(yyDollar[1].str); exists {
				yyVAL.typ = t
			} else {
				yyVAL.typ = &domain.TypeError{Message: fmt.Sprintf("unknown type: %s", yyDollar[1].str)}
			}
		}
	case 25:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			size, _ := strconv.ParseInt(yyDollar[2].token.Value, 10, 32)
			yyVAL.typ = &domain.ArrayType{
				ElementType: yyDollar[4].typ,
				Size:        int(size),
			}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.typ = &domain.ArrayType{
				ElementType: yyDollar[3].typ,
				Size:        -1, // dynamic array
			}
		}
	case 27:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.stmts = []domain.Statement{}
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[2].stmt)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.stmt = &domain.VarDeclStmt{
				BaseNode:    domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Name:        yyDollar[2].str,
				Type_:       yyDollar[3].typ,
				Initializer: nil,
			}
		}
	case 38:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.stmt = &domain.VarDeclStmt{
				BaseNode:    domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Name:        yyDollar[2].str,
				Type_:       yyDollar[3].typ,
				Initializer: yyDollar[5].expr,
			}
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.stmt = &domain.AssignStmt{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Target:   yyDollar[1].expr,
				Value:    yyDollar[3].expr,
			}
		}
	case 40:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.stmt = &domain.IfStmt{
				BaseNode:  domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Condition: yyDollar[3].expr,
				ThenStmt:  yyDollar[5].stmt,
				ElseStmt:  nil,
			}
		}
	case 41:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.stmt = &domain.IfStmt{
				BaseNode:  domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Condition: yyDollar[3].expr,
				ThenStmt:  yyDollar[5].stmt,
				ElseStmt:  yyDollar[7].stmt,
			}
		}
	case 42:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.stmt = &domain.WhileStmt{
				BaseNode:  domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Condition: yyDollar[3].expr,
				Body:      yyDollar[5].stmt,
			}
		}
	case 43:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.stmt = &domain.ForStmt{
				BaseNode:  domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Init:      yyDollar[3].stmt,
				Condition: yyDollar[4].expr,
				Update:    yyDollar[6].stmt,
				Body:      yyDollar[8].stmt,
			}
		}
	case 44:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.stmt = &domain.ForStmt{
				BaseNode:  domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Init:      nil,
				Condition: yyDollar[4].expr,
				Update:    yyDollar[6].stmt,
				Body:      yyDollar[8].stmt,
			}
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.stmt = &domain.ReturnStmt{
				BaseNode: domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Value:    nil,
			}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.stmt = &domain.ReturnStmt{
				BaseNode: domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Value:    yyDollar[2].expr,
			}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.stmt = &domain.ExprStmt{
				BaseNode:   domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Expression: yyDollar[1].expr,
			}
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.stmt = &domain.BlockStmt{
				BaseNode:   domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Statements: yyDollar[2].stmts,
			}
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Add,
				Right:    yyDollar[3].expr,
			}
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Sub,
				Right:    yyDollar[3].expr,
			}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Mul,
				Right:    yyDollar[3].expr,
			}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Div,
				Right:    yyDollar[3].expr,
			}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Mod,
				Right:    yyDollar[3].expr,
			}
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Eq,
				Right:    yyDollar[3].expr,
			}
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Ne,
				Right:    yyDollar[3].expr,
			}
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Lt,
				Right:    yyDollar[3].expr,
			}
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Le,
				Right:    yyDollar[3].expr,
			}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Gt,
				Right:    yyDollar[3].expr,
			}
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Ge,
				Right:    yyDollar[3].expr,
			}
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.And,
				Right:    yyDollar[3].expr,
			}
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.BinaryExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Left:     yyDollar[1].expr,
				Operator: domain.Or,
				Right:    yyDollar[3].expr,
			}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &domain.UnaryExpr{
				BaseNode: domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Operator: domain.Neg,
				Operand:  yyDollar[2].expr,
			}
		}
	case 66:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = &domain.UnaryExpr{
				BaseNode: domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
				Operator: domain.Not,
				Operand:  yyDollar[2].expr,
			}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 68:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.expr = &domain.CallExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Function: yyDollar[1].expr,
				Args:     yyDollar[3].exprs,
			}
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.CallExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Function: yyDollar[1].expr,
				Args:     []domain.Expression{},
			}
		}
	case 70:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.expr = &domain.IndexExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Object:   yyDollar[1].expr,
				Index:    yyDollar[3].expr,
			}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = &domain.MemberExpr{
				BaseNode: domain.BaseNode{Location: yyDollar[1].expr.GetLocation()},
				Object:   yyDollar[1].expr,
				Member:   yyDollar[3].str,
			}
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.exprs = []domain.Expression{yyDollar[1].expr}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = &domain.IdentifierExpr{
				BaseNode: domain.BaseNode{Location: getLocationFromString(yyDollar[1].str)},
				Name:     yyDollar[1].str,
			}
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			// Handle literals that come as identifiers
			if yyDollar[1].token.Value == "true" {
				yyVAL.expr = &domain.LiteralExpr{
					BaseNode: domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
					Value:    true,
				}
			} else if yyDollar[1].token.Value == "false" {
				yyVAL.expr = &domain.LiteralExpr{
					BaseNode: domain.BaseNode{Location: getLocationFromToken(yyDollar[1].token)},
					Value:    false,
				}
			} else {
				// Regular identifier
				yyVAL.expr = &domain.IdentifierExpr{
					BaseNode: domain.BaseNode{Location: getLocationFromString(yyDollar[1].token.Value)},
					Name:     yyDollar[1].token.Value,
				}
			}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].token.Value
		}
	}
	goto yystack /* stack new state and value */
}
